image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DEV_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$TAG
  ENV_TAG : $BUILD

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $DEV_TAG --build-arg ENVIRONMENT=$ENV_TAG .
    - docker push $DEV_TAG
  when: manual